import js from '@eslint/js';

export default [
    js.configs.recommended,
    {
        languageOptions: {
            ecmaVersion: 2022,
            sourceType: 'module',
            globals: {
                window: 'readonly',
                document: 'readonly',
                console: 'readonly',
                localStorage: 'readonly',
                sessionStorage: 'readonly',
                fetch: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                setInterval: 'readonly',
                clearInterval: 'readonly',
                alert: 'readonly',
                confirm: 'readonly',
                navigator: 'readonly',
                URLSearchParams: 'readonly',
                FormData: 'readonly',
                HTMLElement: 'readonly',
                Event: 'readonly',
                AbortController: 'readonly',
                URL: 'readonly',
                Blob: 'readonly',
                FileReader: 'readonly',
                CustomEvent: 'readonly',
                MutationObserver: 'readonly',
                location: 'readonly',
                history: 'readonly',
                prompt: 'readonly',
                showToast: 'readonly',
                closeModal: 'readonly',
                startTour: 'readonly',
            },
        },
        rules: {
            'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
            'no-undef': 'error',
            'no-constant-condition': 'warn',
            'no-debugger': 'error',
            'no-duplicate-case': 'error',
            'no-empty': 'warn',
            'no-extra-semi': 'warn',
            'no-unreachable': 'error',
            'eqeqeq': ['warn', 'always'],
            'no-eval': 'error',
            'no-implied-eval': 'error',
            'no-var': 'warn',
            'prefer-const': 'warn',
        },
    },
    {
        ignores: ['node_modules/', 'coverage/', 'functions/'],
    },
];
